language: python

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

env:
  - DJANGO="django==1.9.2"
  - DJANGO="django==1.8.9"
  - DJANGO="django==1.7.10"

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="django==1.7.10"

    - python: "3.3"
      env: DJANGO="django==1.9.2"

install:
  - travis_retry pip install $DJANGO
  - travis_retry pip install six
  - travis_retry pip install sampledata
  - travis_retry pip install nose
  - travis_retry pip install django-nose
  - travis_retry pip install pillow
  - travis_retry pip install coveralls

script:
  - coverage run --source=sampledatahelper setup.py test

after_success:
  - travis_retry coveralls
